wydsodifficult/wydsodifficult.github.io

ToDo.md

Jacob Initial Push

---

blank.html

- Bug that was not letting drop downs in the sidebar properly work
- Fixed by moving jquery.js source link to bottom of file rather than in the header

Fixed bug in blank.html

---

blank.html
employees-navbar.html
js/app.js
operations-navbar.html

- Also included respective symbols for each sidebar section
Added hideNav() function to employees-navbar and operations-navbar to hide the other when loading
- hideNav() is run in app.js on document ready

Finished Static Sidebar for operation and employee views

---

blank.html
css/style.css
js/app.js
login.html

App.js has firebase initialization and HTML5 local storage check
Created login.html (needs editing)

Blank.html has firebase initialization and user authentication

---

blank.html
js/app.js
register.html

Added passCheck() and passMinCheck() to app.js

Created Register.html for firebase company creation.

---

blank.html
create-company-profile.html
js/app.js

Create-company-profile.html static section works
App.js has new comments in sections

Register.html actually works to create companies

---

blank.html
create-company-profile.html
js/app.js
operations-dashboard.html
register.html

All pages check if user in localStorage matches current user, if not then grabs data from firebase and updates localStorage

Create-company-profile updates company profile and profile of main user

---

blank.html
js/app.js
operations-company.html
operations-jobs.html
operations-report-templates.html
operations-seats.html

Added a loading animation in Operations-jobs while Firebase is grabbing the jobs

Fixed all Sidebar logouts not working

---

employees-reports-new.html
operations-reports-new.html

Operations: moved onfocus:blur() to the button clicked

Trying some fancy things in the new Reports Pages

---

index.html
js/app.js
operations-reports.html

Need to add further search for Type, Job #, Date, and by Person (maybe)

Finished Page for Viewing Reports for Operations

---

js/app.js
login.html

Register button on login page now works and has actual words

Login redirect sends you to what your settings pages requests.

---

employees-company.html
employees-profile.html
js/app.js
operations-seats.html

Readded ability to remove users from operations-seats

---

employees-reports-mine.html
employees-reports-new.html
employees-reports.html
js/app.js
js/jstopdf.js
operations-reports-new.html
operations-reports.html

Operations-reports
Operations-reports-new
Employees-reports
Employees-reports-mine
Employees-reports-new
jstopdf

Changed all "Progress" to "Tasks"

---

coming_soon/js/main.js
employees-profile.html
footer.html
js/app.js
login.html

Changed login "Registration" button

---

employees-reports-mine.html
employees-reports.html
js/app.js
operations-reports.html

Changed the order of viewed reports from descending to ascending.

Added in missing div break so that Custom Template fields can be shown when viewing submitted reports.

---

employees-reports-mine.html
employees-reports.html
js/app.js
operations-reports.html
settings.html

Added in "Submitted By" field in View All for Operations & Employees
Added Settings Option to Hide non-filled fields when viewing reports (Still shows all when downloading)

Added in Feather Requests per Users

---

employees-company.html
footer.html
js/app.js
operations-company.html

Can only be edited after company has been created.

Added in ability for company info to hold additional information.

---

js/app.js

Changed ordering of fetching user data.

Added in removal of missing localStorage.

---

employees-reports-mine.html
employees-reports.html
footer.html
js/app.js
operations-reports.html

Three main fields now: title, costCode, costCodeFillable
If viewing an old format then edit then save, it will convert to new system

Revamped how non-DPR templates fields work for modularity

---

js/app.js
js/jstopdf.js

Added download support for new template format

Fixed Cost Code Name not saving

---

employees-reports-mine.html
employees-reports-new.html
employees-reports.html
js/app.js
js/jstopdf.js
operations-reports-new.html
operations-reports-templates.html
operations-reports.html

Level 1 will have to select whether to include lunch when creating templates
To be used later for Timesheets

Added in lunch option to templates

---

employees-reports-new.html
js/app.js
operations-reports-new.html

Fixed template added lunch displaying incorrectly and to save new/edited correctly

Multiple changes to templates

---

changelog.html
css/style.css
employees-reports-new.html
footer.html
js/app.js
operations-reports-new.html

Changed New Report Total Time value to "Not Yet Set"
Added Catch for Errors when saving a new report
Reincluded NaN for Total Time when saving reports

Small Quality of Life Changes
